In [7]:
#factorial
n = int(input("enter num"))
i=1
fact = 1
while(i<=n):
    fact = fact*i
    i=i+1
print("fact of",n,"is",fact)

enter num 5


fact of 5 is 120


In [10]:
#fibonacci
n1= 0
n2= 1
n = int(input("enter num"))
i= 1
while(i<=n):
    print(n1)
    nnth = n1+n2
    n1 = n2
    n2 = nnth
    i=i+1 #not i++

enter num 6


0
1
1
2
3
5


In [44]:
#string palindrome
str1 = input("enter string")
str1 = str1.replace(" ","").lower()
strrev = str1[::-1]
if(str1 == strrev):
    print(str1,"is palindrome")
else:
    print(str1,"is not palindrome")

enter string HSWSI eue@HEs


hswsieue@hes is not palindrome


In [15]:
#number palindrome
num = int(input("enter num"))
ognum = num
revnum = 0
while(num>0):
    digit = num%10
    revnum = revnum*10+digit
    num = num//10
if(ognum == revnum):
    print(ognum,"is palindrome")
else:
    print(ognum,"is not palindrome")

enter num 545


545 is palindrome


In [7]:
#number digit addition
def sum_digit():
    num = int(input("enter num"))
    num1 = num
    addn = 0
    while(num>0):
        digit = num % 10
        addn = addn + digit
        num = num//10
    print("addition of digits of number:", num1)

sum_digit()

enter num 787


addition of digits of number: 787


In [27]:
#if else ladder
percentage = int(input("enter percentage"))
if(percentage>=90 and percentage<=100):
    print("A+")
elif(percentage>=80 and percentage<=89):
    print("A")
elif(percentage>=60 and percentage<=79):
    print("B")
elif(percentage>=35 and percentage<=59):
    print("C")
elif(percentage>=0 and percentage<=34):
    print("F")
else:
    print("invalid %")

enter percentage 94


A+


In [35]:
#greatest among 4 numbers
n1= int(input("enter num1"))
n2= int(input("enter num2"))
n3= int(input("enter num3"))
n4= int(input("enter num4"))
print("greatest:")
if(n1 > n2 and n1 > n3 and n1 > n4):
    print(n1)
elif(n2 > n3 and n2 > n4 and n2 > n1):
    print(n2)
elif(n3 > n4 and n3 > n1 and n3 > n2):
    print(n3)
else:
    print(n4)

enter num1 1
enter num2 2
enter num3 3
enter num4 4


greatest:
4


In [46]:
#matchcase in python
gender = input("enter your gender")
match gender:
    case "male":
        print("you are male")
    case "female":
        print("you are female")
    case _:
        print("you are gay")


enter your gender amit


you are gay


In [4]:
#module creation and import (only function) with alias
'''
mymodule_withfunc.py
def numguess():
    n = int(input("enter num you choosen in mind"))
    print("your number:",n,"\nmy prediction:",n)
def letguess():
    n = int(input("enter letter you choosen in mind"))
    print("your letter:",n,"\nmy prediction:",n)
'''

import mymodule_withfunc as mmf
mmf.letguess()
mmf.numguess()

enter letter you choosen in mind d


your letter: d 
my prediction: d


enter num you choosen in mind 4


your number: 4 
my prediction: 4


In [3]:
#module creation and import (class and function)
'''
mymodule_withclass.py
class student:
    def getdata(self):
        self.name= input("enter student name")
        self.rollno= int(input("enter rollno"))
    def setdata(self):
        print("name:",self.name)
        print("roll no:",self.rollno)
clg = "JSPM"
'''
from mymodule_withclass import student
amit= student()
amit.getdata()
amit.setdata()
# amit.rollno

import mymodule_withclass
print("clg:",mymodule_withclass.clg)

# import mymodule_withclass
# a = mymodule_withclass.student()
# a.getdata()
# a.setdata()

enter student name am
enter rollno 33


name: am
roll no: 33
clg: JSPM


In [5]:
#user defined package
'''
mypackage
|- __init__.py
|- mymodule.py

mymodule.py
class student:
    def getdata(self):
        self.name= input("enter student name")
        self.rollno= int(input("enter rollno"))
    def setdata(self):
        print("name:",self.name)
        print("roll no:",self.rollno)
clg = "JSPM"
'''

from mypackage.mymodule import student as s1
amit = s1()
amit.getdata()
amit.setdata()

enter student name amit
enter rollno 34


name: amit
roll no: 34


In [39]:
#generate random elements betn range
import numpy as np
n = int(input("enter how many numbers to generate"))
for i in range(n):
    print(np.random.randint(10,50))

enter how many numbers to generate 2


37
40


In [41]:
#array declaration and addition
a = np.array([1,2,3]) #1d
print(a)
b = np.array([[1,2,3],[3,4,5]]) #md
b = np.append(b,[[6,7,8]],axis=0)
print(b)

[1 2 3]
[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [47]:
#read and display data in class
class Student:
    def read(self):
        self.name = input("enter name")
        self.rollno = int(input("enter rollno"))
    def write(self):
        print("name:{}\nroll no:{}".format(self.name,self.rollno))

amit = student()
amit.read()
amit.write()

enter name amit
enter rollno 222


name:amit
roll no:222


In [60]:
#single inheritance
class College:
    def __init__(self,cname):
        self.cname=cname
class Student(College):
    def __init__(self,cname,sname):
        super().__init__(cname)
        self.sname=sname
    def show(self):
        print("{} is stuent of {}".format(self.sname,self.cname))
        
amit = Student("jspm","amit")
amit.show()

amit is stuent of jspm


In [68]:
#single inheritance v2
class Parent:
    def __init__(self):
        print("Default constuctor of Parent called")
    def read_data(self):
        self._parent_name = input("enter parent class name")
        print("{} is parent class name".format(self._parent_name))
class Child(Parent):
    def __init__(self,child_name):
        self.child_name = child_name
        super().__init__()
    def write_data(self):
        print("{} is child class name of parent class {}".format(self.child_name,self._parent_name))

amit = Child("amit")
amit.read_data()
amit.write_data()

Default constuctor of Parent called


enter parent class name sarthak


sarthak is parent class name
amit is child class name of parent class sarthak


In [74]:
#multiple inheritance:
class MAD:
    def __init__(self):
        print("MAD Constructor called")
    def get_mad_data(self):
        self.mad_marks = int(input("enter mad marks"))
        print
class PWP:
    def __init__(self):
        print("PWP constructor called")
    def get_pwp_data(self):
        self.pwp_marks = int(input("enter pwp marks"))
class Student(MAD,PWP):
    def __init__(self,name,rollno):
        print("Student constructor called")
        self.name = name
        self.rollno = rollno
        MAD.__init__(self)
        PWP.__init__(self)
    def put_result(self):
        self.total_marks = 140
        self.obtained_marks = self.mad_marks + self.pwp_marks
        self.percentage = (self.obtained_marks/self.total_marks)*100
        print("{} has got {}%".format(self.name,self.percentage))

amit = Student("amit",92)
amit.get_mad_data()
amit.get_pwp_data()
amit.put_result()

Student constructor called
MAD Constructor called
PWP constructor called


enter mad marks 68
enter pwp marks 68


amit has got 97.14285714285714%


In [84]:
#multilevel inheritance
class Grandfather:
    def __init__(self):
        print("i am grandfather constructor")
    def get_gfname(self):
        self.gfname = input("enter grandfather name")
class Father(Grandfather):
    def __init__(self):
        print("i am father constructor")
    def get_fname(self):
        self.fname = input("enter father name")
class Son(Father):
    def __init__(self,sname):
        self.sname = sname
    def show_hierarchy(self):
        Father.__init__(self)
        print("my name is {} father of {}".format(self.fname,self.sname))
        Grandfather.__init__(self)
        print("my name is {} grandfather of {}".format(self.gfname,self.sname))

amit = Son("amit")
amit.get_gfname()
amit.get_fname()
amit.show_hierarchy()

enter grandfather name baban
enter father name sarthak


i am father constructor
my name is sarthak father of amit
i am grandfather constructor
my name is baban grandfather of amit


In [95]:
#method overloading 
class Shape:
    def __init__(self):
        print("shape constructor got called")
    def area(self,s1,s2=0,s3=0):
        if(s1!=0 and s2==0 and s3==0):
            sq_area = s1**2
            print("area of square is:",sq_area)
        elif(s1!=0 and s2!=0 and s3==0):
            rect_area = s1*s2
            print("area of rectangle is:",rect_area)
        else:
            cub_volume = s1*s2*s3
            print("cuboid volume is:",cub_volume)

polygon = Shape()
polygon.area(3,3,3)

shape constructor got called
cuboid volume is: 27


In [96]:
#method overriding
class Shape:
    def __init__(self):
        print("Welcome to Shape")
    def area(self):
        pass
class Square(Shape):
    def __init__(self):
        print("welcome to Square")
    def area(self,s1):
        sq_area = s1**2
        print("area of square is:",sq_area)
class Rectangle(Shape):
    def __init__(self):
        print("welcome to Rectangle")
    def area(self,s1,s2):
        rect_area = s1*s2
        print("area of rectangle is:",rect_area)

sq = Square()
sq.area(5)
rect = Rectangle()
rect.area(5,10)

welcome to Square
area of square is: 25
welcome to Rectangle
area of rectangle is: 50


In [101]:
#try catch block with UD exception
class ShortPasswordException(Exception):
    pass
def check_password(password):
    if(len(password)<8):
        raise ShortPasswordException("length is too short!")

def user():
    user_name = input("set user name")
    user_pass = input("set password")
    check_password(user_pass)

try:
    user()
except ShortPasswordException as spe:
    print("Oh no,",spe)
except IOError as ioe:
    print("Oh no,",ioe)
else:
    print("congrats!!! your password is valid")
finally:
    print("This was account setup process")

set user name sarthak
set password sp11


Oh no, length is too short!
This was account setup process


In [132]:
#file copy paste
f = open("f1.txt","w")
f.write("hello world\nbye world")
f.close()

f = open("f1.txt","r")
contents = f.read()
f.close()

f = open("f2.txt","w")
f.write(contents)
f.close()

f = open("f2.txt","r")
contents = f.read()
print(contents)
f.close()

44
0
hello world
bye world this is appended text


In [ ]:
#append
f = open("f2.txt","a+")
# f.write(" this is appended text")
print(f.tell())
f.seek(0)
print(f.tell())
contents = f.read()
print(contents)

In [138]:
#char freq count
from collections import Counter
f = open("f2.txt","r")
contents = f.read()
char_freq = Counter(contents)
for char, freq in char_freq.items():
    print("char:",char,"freq:",freq)
f.close()

char: h freq: 1
char: e freq: 1
char: l freq: 2
char: o freq: 1


In [144]:
#read,readline,readlines
f = open("f1.txt","r")

#read
contents_read = f.read()
print(contents_read,"\n")

#readline
f.seek(0)
contents_readline = ""
while(True):
    line = f.readline()
    if(line==""):
        break
    contents_readline = contents_readline + line
print(contents_readline,"\n")

#readlines
f.seek(0)
content_readlines = ""
lines = f.readlines()
for line in lines:
    content_readlines = content_readlines + line
print(content_readlines)

hello world
bye world 

hello world
bye world 

hello world
bye world


In [145]:
#cli sys.argv
import sys
if(len(sys.argv)!=3):
    print("enter like: python filename num1 num2")
else:
    n1 = sys.argv[0]
    n2 = sys.argv[1]
    addn = n1 + n2
    print("addn:",addn)

addn: C:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py-f
